<?php
/* 
    Subject    : OFF CAMPUS PLATFORM PROJECT
    Created on : 09-Mar-2019, 01:52:54 PM
    Author     : Marc Freir
    License    : This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.
*/
?>

<?php
    class SIGNATURE
    {
        private $msg;
        private $privateKey;

        function __contruct($msg, $privateKey)
        {
            
        }
    }
?>